### PR TITLE
Fix #19 nginx root

### LINKED ISSUE #19: Nginx Hosts - Root should be a variable
Create a variable to defined root of project.
Currently, hosts root directory is fixed.

### PR DESCRIPTION
**Pull request by jygastaud**

### CODE REVIEW

**Comment by jygastaud** [comment]
Live demo : https://lumberjack-fork.herokuapp.com/

**Comment by FlorianLB** [comment]
:+1: for configurable nginx root

But I would prefer to automatically fill this variable depending on selected project framework. This project should not be a Phansible clone, it aims to assume certain things. What do you think ?

**Comment by jygastaud** [comment]
We discuss that today.

Here is my new proposal:
1. At the moment, remove configuration part from the FO and only keep variable generated.
2. We can add a default variable for both drupal and symfony
3. We can discuss FO configuration needs in a seperated issue

We can deal quickly with 1 and 2.

**Comment by FlorianLB** [comment]
:+1:

**Comment by jygastaud** [comment]
Should be OK for 1 and 2 now.

**Comment by FlorianLB** [comment]
Thx !

**Pull request merged**
